rule powershell_obfuscation
{
    meta:
      author = "ionstorm"
      type = "Microsoft-Windows-PowerShell"
      description = "Powershell Obfuscation Detections"

    strings:
      $s0 = "FromBase64" ascii wide nocase
      $s1 = "AAAAYInlM" ascii wide nocase
      $s2 = "OiCAAAAYInlM" ascii wide nocase
      $s3 = "aHR0cDovL" ascii wide nocase
      $s4 = "h0dHA6Ly" ascii wide nocase
      $s5 = "odHRwOi8v" ascii wide nocase
      $s6 = "aHR0cHM6Ly" ascii wide nocase
      $s7 = "h0dHBzOi8v" ascii wide nocase
      $s8 = "odHRwczovL" ascii wide nocase
      $s9 = "BNAG8AegBpAGwAbABhAC" ascii wide nocase
      $s10 = "0AbwB6AGkAbABsAGEAL" ascii wide nocase
      $s11 = "TQBvAHoAaQBsAGwAYQAv" ascii wide nocase
      $s12 = "TW96aWxsYS" ascii wide nocase
      $s13 = "1vemlsbGEv" ascii wide nocase
      $s14 = "aQBlAHgA" ascii wide nocase
      $s15 = "aWV4I" ascii wide nocase
      $s16 = " iex " ascii wide nocase
      $s17 = "%C^om^S^pEc%" ascii wide nocase
      $s18 = "%^c^o^m^S^p^E^c^%" ascii wide nocase
      $s19 = "%comspec%" ascii wide nocase
      $s20 = "-ComObject" ascii wide nocase
      $s21 = "-NoP " ascii wide nocase
      $s22 = "-NoPr " ascii wide nocase
      $s23 = "-NoPro " ascii wide nocase
      $s24 = "-NoProf " ascii wide nocase
      $s25 = "-NoProfi " ascii wide nocase
      $s26 = "-NoProfil " ascii wide nocase
      $s27 = "-NoProfile " ascii wide nocase
      $s28 = "-Nop -e" ascii wide nocase
      $s29 = "-UseB" ascii wide nocase
      $s30 = "-e " ascii wide nocase
      $s31 = "-e -nop" ascii wide nocase
      $s32 = "-ec" ascii wide nocase
      $s33 = "-en " ascii wide nocase
      $s34 = "-enc " ascii wide nocase
      $s35 = "-enco " ascii wide nocase
      $s36 = "-encod " ascii wide nocase
      $s37 = "-encode " ascii wide nocase
      $s39 = "-encoded " ascii wide nocase
      $s40 = "-encodedC " ascii wide nocase
      $s41 = "-encodedCo " ascii wide nocase
      $s42 = "-encodedCom " ascii wide nocase
      $s43 = "-encodedComm " ascii wide nocase
      $s44 = "-encodedComma " ascii wide nocase
      $s45 = "-encodedComman " ascii wide nocase
      $s46 = "-encodedCommand" ascii wide nocase
      $s47 = "-noni " ascii wide nocase
      $s48 = "-nonin " ascii wide nocase
      $s49 = "-nonint " ascii wide nocase
      $s50 = "-noninte " ascii wide nocase
      $s51 = "-noninter " ascii wide nocase
      $s52 = "-nonintera " ascii wide nocase
      $s53 = "-noninterac " ascii wide nocase
      $s54 = "-noninteract " ascii wide nocase
      $s55 = "-noninteracti " ascii wide nocase
      $s56 = "-noninteractiv " ascii wide nocase
      $s57 = "-noninteractive " ascii wide nocase
      $s58 = "-w h" ascii wide nocase
      $s59 = "-wi h " ascii wide nocase
      $s60 = "-win h" ascii wide nocase
      $s61 = "-win h " ascii wide nocase
      $s62 = "-win hi " ascii wide nocase
      $s63 = "-win hid " ascii wide nocase
      $s64 = "-win hidd " ascii wide nocase
      $s65 = "-win hidde " ascii wide nocase
      $s66 = "-win hidden " ascii wide nocase
      $s67 = "-wind h" ascii wide nocase
      $s68 = "-windo h" ascii wide nocase
      $s69 = "-windows h" ascii wide nocase
      $s70 = "-windowst h" ascii wide nocase
      $s71 = "-windowsty h" ascii wide nocase
      $s72 = "-windowstyl h" ascii wide nocase
      $s73 = "::DECompreSS" ascii wide nocase
      $s74 = "AdjustTokenPrivileges" ascii wide nocase
      $s75 = "Compression.GzipStream'" ascii wide nocase
      $s76 = "CreateRemoteThread" ascii wide nocase
      $s77 = "DllCharacteristicsType" ascii wide nocase
      $s78 = "DownloadFile" ascii wide nocase
      $s79 = "DownloadString" ascii wide nocase
      $s80 = "FRoMBase64strinG" ascii wide nocase
      $s81 = "FromBase64" ascii wide nocase
      $s82 = "GetDelegateForFunctionPointer" ascii wide nocase
      $s83 = "IMAGE_NT_OPTIONAL_HDR32" ascii wide nocase
      $s84 = "IMAGE_NT_OPTIONAL_HDR64" ascii wide nocase
      $s85 = "IMAGE_SUBSYSTEM_WINDOWS_GUI" ascii wide nocase
      $s86 = "IO.MemoryStream'" ascii wide nocase
      $s87 = "ImpersonateSelf" ascii wide nocase
      $s88 = "Invoke-Expression" ascii wide nocase
      $s89 = "Invoke-WebRequest" ascii wide nocase
      $s90 = "Io.sTReaMReadeR'" ascii wide nocase
      $s91 = "MsXml2.ServerXmlHttp" ascii wide nocase
      $s92 = "Nb3ppbGxhL" ascii wide nocase
      $s93 = "Net.WebClient" ascii wide nocase
      $s94 = "NtCreateThreadEx" ascii wide nocase
      $s95 = "ReadProcessMemory" ascii wide nocase
      $s96 = "Remove.To.String" ascii wide nocase
      $s97 = "Remove.ToString" ascii wide nocase
      $s98 = "SE^T" ascii wide nocase
      $s99 = "SQBFAFgA" ascii wide nocase
      $s100 = "SUVYI" ascii wide nocase
      $s101 = "S^ET" ascii wide nocase
      $s102 = "Shellcode" ascii wide nocase
      $s103 = "System.Net.SecurityProtocolType" ascii wide nocase
      $s104 = "System.Net.WebClient" ascii wide nocase
      $s105 = "System.Net.WebRequest" ascii wide nocase
      $s106 = "TExT.enC" ascii wide nocase
      $s107 = "VerbosePreference" ascii wide nocase
      $s108 = "WriteProcessMemory" ascii wide nocase
      $s109 = "Wscript.Shell" ascii wide nocase
      $s110 = "[Byte[]" ascii wide nocase
      $s111 = "[Convert]::" ascii wide nocase
      $s112 = "[IO.File]::ReadAllBytes" ascii wide nocase
      $s113 = "[[string]::Join" ascii wide nocase
      $s114 = "^(^" ascii wide nocase
      $s115 = "^;^" ascii wide nocase
      $s116 = "^A" ascii wide nocase
      $s117 = "^B" ascii wide nocase
      $s118 = "^C" ascii wide nocase
      $s119 = "^D" ascii wide nocase
      $s120 = "^E" ascii wide nocase
      $s121 = "^F" ascii wide nocase
      $s122 = "^G" ascii wide nocase
      $s123 = "^H" ascii wide nocase
      $s124 = "^I" ascii wide nocase
      $s125 = "^J" ascii wide nocase
      $s126 = "^K" ascii wide nocase
      $s127 = "^L" ascii wide nocase
      $s128 = "^M" ascii wide nocase
      $s129 = "^N" ascii wide nocase
      $s130 = "^O" ascii wide nocase
      $s131 = "^P" ascii wide nocase
      $s132 = "^Q" ascii wide nocase
      $s133 = "^R" ascii wide nocase
      $s134 = "^S" ascii wide nocase
      $s135 = "^T" ascii wide nocase
      $s136 = "^U" ascii wide nocase
      $s137 = "^V" ascii wide nocase
      $s138 = "^W" ascii wide nocase
      $s139 = "^X" ascii wide nocase
      $s140 = "^Y" ascii wide nocase
      $s141 = "^Z" ascii wide nocase
      $s142 = "^c^o^m^S^p^E^c^" ascii wide nocase
      $s143 = "convertto-securestring" ascii wide nocase
      $s144 = "eXEcUTIoNcONTExt" ascii wide nocase
      $s145 = "hextobin" ascii wide nocase
      $s146 = "io.CoMprESsIoN'" ascii wide nocase
      $s147 = "io.filestream" ascii wide nocase
      $s148 = "io.seekorigin" ascii wide nocase
      $s149 = "iwr " ascii wide nocase
      $s150 = "runtime.interopservices" ascii wide nocase
      $s151 = "sYsTem.io.cOMpReSsiON" ascii wide nocase
      $s152 = "s^et" ascii wide nocase
      $s153 = "sySTem.TExT.ENcodInG" ascii wide nocase
      $s154 = "syStem.IO.MEMOrYstreAm" ascii wide nocase
      $s155 = "system.convert'" ascii wide nocase
      $s156 = "tEXT.encODiNG" ascii wide nocase
      $s157 = "unicode.getstring" ascii wide nocase
      $s158 = "ToBase64String" ascii wide nocase
      $s159 = "net.WebRequest" ascii wide nocase

    condition:
      any of ($s*)
}
